#!/bin/bash
# Quick update for Bedrock Pi 5 - Generated by deploy script

PI_HOST="192.168.1.243"
PI_USER="standa"
PI_PASS="crossover"
LOCAL_PROJECT_PATH="/mnt/c/_PROJECTS/Bedrock_2.0"
REMOTE_APP_PATH="/home/standa/bedrock-app"

echo "🔄 Quick update - syncing changed files..."

# Stop app
sshpass -p "$PI_PASS" ssh -o StrictHostKeyChecking=no "$PI_USER@$PI_HOST" "pkill -f 'python.*main.py' || true"

# Sync files
sshpass -p "$PI_PASS" rsync -avz --checksum \
    --exclude="__pycache__" --exclude="*.pyc" --exclude=".git" --exclude="venv" --exclude="logs/*.log" \
    -e "ssh -o StrictHostKeyChecking=no" \
    "$LOCAL_PROJECT_PATH/" "$PI_USER@$PI_HOST:$REMOTE_APP_PATH/"

echo "✅ Files synced. App will restart automatically via autostart."
echo "Manual start: ssh $PI_USER@$PI_HOST '/home/standa/manage_bedrock.sh start'"
