#:kivy 2.2.1
#:import MDLabel kivymd.uix.label.MDLabel
#:import MDIconButton kivymd.uix.button.MDIconButton
#:import MDBoxLayout kivymd.uix.boxlayout.MDBoxLayout
#:import MDTopAppBar kivymd.uix.toolbar.MDTopAppBar

<HomeScreen>:
    name: "home"

    BoxLayout:
        orientation: "vertical"

        # Верхнее меню
        MDTopAppBar:
            title: "Bedrock"
            left_action_items: [["menu", lambda x: app.on_menu_button()]]
            right_action_items: [["cog", lambda x: app.on_settings_button()]]
            elevation: 4

        # Основной контент
        MDBoxLayout:
            orientation: "vertical"
            padding: "24dp"
            spacing: "16dp"

            MDLabel:
                text: "Главный экран"
                halign: "center"
                font_style: "H4"

            MDLabel:
                text: "Здесь будут часы, погода, уведомления и т.п."
                halign: "center"
